export interface TechGroup {
  name: string;
  /** What this layer does, in plain language. */
  plain: string;
  tools: string[];
}

/** Technology we work with, grouped by layer. Shown on the homepage. */
export const techStack: TechGroup[] = [
  {
    name: "Front end",
    plain: "The pages and screens your customers see, tap and click.",
    tools: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Astro", "Vue", "Tailwind CSS"],
  },
  {
    name: "Back end and APIs",
    plain: "The logic behind the scenes that saves data, sends emails and connects systems.",
    tools: ["Node.js", "Python", "Go", "REST APIs", "GraphQL", "WebSockets", "Serverless functions"],
  },
  {
    name: "Databases",
    plain: "Where your information is stored safely and found again quickly.",
    tools: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Supabase", "Prisma", "Elasticsearch"],
  },
  {
    name: "AI and machine learning",
    plain: "Assistants and tools that read, write, sort and answer questions from your data.",
    tools: [
      "OpenAI",
      "Anthropic Claude",
      "Google Gemini",
      "Open-weight models (Llama, Mistral)",
      "Retrieval-augmented generation",
      "Vector search (pgvector)",
      "LangChain",
      "Evaluation and monitoring",
    ],
  },
  {
    name: "Cloud and DevOps",
    plain: "Reliable hosting, automatic backups and safe, repeatable releases.",
    tools: ["AWS", "Microsoft Azure", "Google Cloud", "Vercel", "Cloudflare", "Docker", "GitHub Actions", "Terraform"],
  },
  {
    name: "Content, commerce and payments",
    plain: "Tools your team uses to edit the website, sell online and take payments.",
    tools: ["WordPress", "Sanity", "Contentful", "Shopify", "Stripe", "Webflow"],
  },
  {
    name: "Automation and integrations",
    plain: "Connections that move information between the software you already use.",
    tools: ["n8n", "Make", "Zapier", "Salesforce", "HubSpot", "NetSuite", "QuickBooks", "Microsoft 365", "Slack"],
  },
  {
    name: "Quality, security and performance",
    plain: "Testing and monitoring that catch problems before your customers do.",
    tools: ["Playwright", "Vitest", "Lighthouse", "Core Web Vitals", "Sentry", "OWASP practices", "Accessibility (WCAG 2.2)"],
  },
];

/** Full catalog shown on the Technology page, split into web and AI. */
export const webCatalog: TechGroup[] = [
  {
    name: "Languages",
    plain: "The core languages the web and modern software are written in.",
    tools: ["HTML5", "CSS3", "JavaScript (ES2025)", "TypeScript", "Python", "Go", "Rust", "PHP", "C#", "SQL"],
  },
  {
    name: "Front-end frameworks",
    plain: "Frameworks that turn designs into fast, interactive pages and apps.",
    tools: [
      "React 19",
      "Next.js",
      "Vue",
      "Nuxt",
      "Svelte",
      "SvelteKit",
      "Angular",
      "Astro",
      "React Router (Remix)",
      "SolidJS",
      "htmx",
    ],
  },
  {
    name: "Styling and UI",
    plain: "How your product looks and stays consistent on every screen size.",
    tools: [
      "Tailwind CSS",
      "Sass",
      "CSS Modules",
      "shadcn/ui",
      "Radix UI",
      "Headless UI",
      "Framer Motion",
      "Figma",
      "Storybook",
    ],
  },
  {
    name: "Mobile and desktop",
    plain: "Apps for phones and computers that share code with your website.",
    tools: ["React Native", "Expo", "Progressive Web Apps", "Flutter", "Capacitor", "Electron", "Tauri"],
  },
  {
    name: "Back end and runtimes",
    plain: "The servers and logic behind your product: accounts, orders, emails and more.",
    tools: [
      "Node.js",
      "Bun",
      "Deno",
      "Express",
      "Fastify",
      "NestJS",
      "Hono",
      "Django",
      "FastAPI",
      "Laravel",
      ".NET",
    ],
  },
  {
    name: "APIs and real time",
    plain: "How your systems talk to each other and update instantly.",
    tools: ["REST", "GraphQL", "tRPC", "gRPC", "WebSockets", "Server-Sent Events", "Webhooks", "OpenAPI"],
  },
  {
    name: "Databases and data",
    plain: "Where your information is stored, searched and kept safe.",
    tools: [
      "PostgreSQL",
      "MySQL",
      "SQL Server",
      "SQLite",
      "MongoDB",
      "Redis",
      "Supabase",
      "Firebase",
      "Neon",
      "Elasticsearch",
      "ClickHouse",
      "Prisma",
      "Drizzle ORM",
    ],
  },
  {
    name: "Cloud, hosting and DevOps",
    plain: "Reliable hosting, automatic backups and safe, repeatable releases.",
    tools: [
      "AWS",
      "Microsoft Azure",
      "Google Cloud",
      "Vercel",
      "Netlify",
      "Cloudflare Workers",
      "Fly.io",
      "DigitalOcean",
      "Docker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "GitLab CI",
    ],
  },
  {
    name: "Authentication and payments",
    plain: "Secure sign-in for your users and reliable ways to get paid.",
    tools: ["Auth.js", "Clerk", "Auth0", "Microsoft Entra ID", "Passkeys", "OAuth 2.0", "Stripe", "PayPal", "Square"],
  },
  {
    name: "CMS and e-commerce",
    plain: "Tools your team uses to edit content and sell online.",
    tools: [
      "WordPress",
      "Sanity",
      "Contentful",
      "Strapi",
      "Payload",
      "Webflow",
      "Shopify",
      "Shopify Hydrogen",
      "WooCommerce",
    ],
  },
  {
    name: "Testing, performance and monitoring",
    plain: "Checks that catch problems early and keep your site fast and secure.",
    tools: [
      "Playwright",
      "Cypress",
      "Vitest",
      "Jest",
      "Vite",
      "Turbopack",
      "Lighthouse",
      "Core Web Vitals",
      "Sentry",
      "Datadog",
      "PostHog",
      "Google Analytics 4",
      "OWASP practices",
    ],
  },
];

export const aiCatalog: TechGroup[] = [
  {
    name: "AI models",
    plain: "The AI engines that read, write, summarize and reason. We pick the right one for each job.",
    tools: [
      "OpenAI GPT",
      "OpenAI o-series reasoning models",
      "Anthropic Claude",
      "Google Gemini",
      "Meta Llama",
      "Mistral",
      "DeepSeek",
      "Qwen",
      "Cohere",
      "xAI Grok",
    ],
  },
  {
    name: "AI platforms and hosting",
    plain: "Secure places to run AI, including options that keep your data inside your own cloud.",
    tools: [
      "Azure AI Foundry",
      "Azure OpenAI",
      "Amazon Bedrock",
      "Google Vertex AI",
      "Hugging Face",
      "Ollama",
      "vLLM",
      "Groq",
      "Together AI",
      "Replicate",
    ],
  },
  {
    name: "Agents and frameworks",
    plain: "Building blocks for AI assistants that can take actions and use your tools.",
    tools: [
      "Model Context Protocol (MCP)",
      "OpenAI Agents SDK",
      "Claude Agent SDK",
      "Vercel AI SDK",
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "CrewAI",
      "AutoGen",
      "Pydantic AI",
      "DSPy",
    ],
  },
  {
    name: "Knowledge and search",
    plain: "Letting AI answer from your own documents, with sources you can check.",
    tools: [
      "Retrieval-augmented generation (RAG)",
      "Embeddings",
      "pgvector",
      "Pinecone",
      "Weaviate",
      "Qdrant",
      "Chroma",
      "Azure AI Search",
      "Hybrid and semantic search",
    ],
  },
  {
    name: "Voice, vision and documents",
    plain: "AI that understands speech, images and paperwork like invoices and contracts.",
    tools: [
      "OpenAI Whisper",
      "Realtime voice APIs",
      "ElevenLabs",
      "Deepgram",
      "Azure Document Intelligence",
      "Amazon Textract",
      "Image understanding",
      "Image generation",
    ],
  },
  {
    name: "Customization",
    plain: "Teaching AI your tone, terms and processes when off-the-shelf results aren't enough.",
    tools: ["Prompt engineering", "Structured outputs", "Function and tool calling", "Fine-tuning", "LoRA", "Distillation"],
  },
  {
    name: "Evaluation and monitoring",
    plain: "Measuring accuracy and cost so AI results can be trusted in production.",
    tools: ["LangSmith", "Langfuse", "promptfoo", "Arize Phoenix", "Weights & Biases", "OpenTelemetry", "Custom test sets"],
  },
  {
    name: "Safety and privacy",
    plain: "Controls that protect your data and keep AI answers within the rules.",
    tools: [
      "Guardrails",
      "PII redaction",
      "Role-based access",
      "Human review workflows",
      "Audit logging",
      "Zero data retention options",
    ],
  },
];
