import type { TechGroup, TechnologyContent } from "@/lib/technology";

/** Technology we work with, grouped by layer. Shown on the homepage. */
const techStack: TechGroup[] = [
  {
    name: "Front end",
    plain: "Las páginas y pantallas que sus clientes ven, tocan y usan.",
    tools: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Astro", "Vue", "Tailwind CSS"],
  },
  {
    name: "Back end y API",
    plain: "La lógica detrás de escena que guarda datos, envía correos y conecta sistemas.",
    tools: ["Node.js", "Python", "Go", "API REST", "GraphQL", "WebSockets", "Funciones serverless"],
  },
  {
    name: "Bases de datos",
    plain: "Donde su información se guarda de forma segura y se encuentra rápidamente.",
    tools: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Supabase", "Prisma", "Elasticsearch"],
  },
  {
    name: "IA y aprendizaje automático",
    plain: "Asistentes y herramientas que leen, escriben, clasifican y responden preguntas a partir de sus datos.",
    tools: [
      "OpenAI",
      "Anthropic Claude",
      "Google Gemini",
      "Modelos de pesos abiertos (Llama, Mistral)",
      "Generación aumentada por recuperación",
      "Búsqueda vectorial (pgvector)",
      "LangChain",
      "Evaluación y monitoreo",
    ],
  },
  {
    name: "Nube y DevOps",
    plain: "Alojamiento fiable, copias de seguridad automáticas y publicaciones seguras y repetibles.",
    tools: ["AWS", "Microsoft Azure", "Google Cloud", "Vercel", "Cloudflare", "Docker", "GitHub Actions", "Terraform"],
  },
  {
    name: "Contenido, comercio y pagos",
    plain: "Herramientas que su equipo usa para editar el sitio, vender en línea y cobrar.",
    tools: ["WordPress", "Sanity", "Contentful", "Shopify", "Stripe", "Webflow"],
  },
  {
    name: "Automatización e integraciones",
    plain: "Conexiones que mueven información entre el software que ya usa.",
    tools: ["n8n", "Make", "Zapier", "Salesforce", "HubSpot", "NetSuite", "QuickBooks", "Microsoft 365", "Slack"],
  },
  {
    name: "Calidad, seguridad y rendimiento",
    plain: "Pruebas y monitoreo que detectan los problemas antes que sus clientes.",
    tools: [
      "Playwright",
      "Vitest",
      "Lighthouse",
      "Core Web Vitals",
      "Sentry",
      "Prácticas OWASP",
      "Accesibilidad (WCAG 2.2)",
    ],
  },
];

/** Full catalog shown on the Technology page, split into web and AI. */
const webCatalog: TechGroup[] = [
  {
    name: "Lenguajes",
    plain: "Los lenguajes básicos en los que se escriben la web y el software moderno.",
    tools: ["HTML5", "CSS3", "JavaScript (ES2025)", "TypeScript", "Python", "Go", "Rust", "PHP", "C#", "SQL"],
  },
  {
    name: "Frameworks de front end",
    plain: "Frameworks que convierten los diseños en páginas y aplicaciones rápidas e interactivas.",
    tools: [
      "React 19",
      "Next.js",
      "Vue",
      "Nuxt",
      "Svelte",
      "SvelteKit",
      "Angular",
      "Astro",
      "React Router (Remix)",
      "SolidJS",
      "htmx",
    ],
  },
  {
    name: "Estilos e interfaz",
    plain: "Cómo se ve su producto y cómo se mantiene coherente en cualquier tamaño de pantalla.",
    tools: [
      "Tailwind CSS",
      "Sass",
      "CSS Modules",
      "shadcn/ui",
      "Radix UI",
      "Headless UI",
      "Framer Motion",
      "Figma",
      "Storybook",
    ],
  },
  {
    name: "Móvil y escritorio",
    plain: "Aplicaciones para teléfonos y computadoras que comparten código con su sitio web.",
    tools: ["React Native", "Expo", "Aplicaciones web progresivas", "Flutter", "Capacitor", "Electron", "Tauri"],
  },
  {
    name: "Back end y entornos de ejecución",
    plain: "Los servidores y la lógica detrás de su producto: cuentas, pedidos, correos y más.",
    tools: ["Node.js", "Bun", "Deno", "Express", "Fastify", "NestJS", "Hono", "Django", "FastAPI", "Laravel", ".NET"],
  },
  {
    name: "API y tiempo real",
    plain: "Cómo se comunican sus sistemas entre sí y se actualizan al instante.",
    tools: ["REST", "GraphQL", "tRPC", "gRPC", "WebSockets", "Server-Sent Events", "Webhooks", "OpenAPI"],
  },
  {
    name: "Bases de datos y datos",
    plain: "Donde su información se guarda, se consulta y se mantiene segura.",
    tools: [
      "PostgreSQL",
      "MySQL",
      "SQL Server",
      "SQLite",
      "MongoDB",
      "Redis",
      "Supabase",
      "Firebase",
      "Neon",
      "Elasticsearch",
      "ClickHouse",
      "Prisma",
      "Drizzle ORM",
    ],
  },
  {
    name: "Nube, alojamiento y DevOps",
    plain: "Alojamiento fiable, copias de seguridad automáticas y publicaciones seguras y repetibles.",
    tools: [
      "AWS",
      "Microsoft Azure",
      "Google Cloud",
      "Vercel",
      "Netlify",
      "Cloudflare Workers",
      "Fly.io",
      "DigitalOcean",
      "Docker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "GitLab CI",
    ],
  },
  {
    name: "Autenticación y pagos",
    plain: "Inicio de sesión seguro para sus usuarios y formas fiables de cobrar.",
    tools: ["Auth.js", "Clerk", "Auth0", "Microsoft Entra ID", "Passkeys", "OAuth 2.0", "Stripe", "PayPal", "Square"],
  },
  {
    name: "CMS y comercio electrónico",
    plain: "Herramientas que su equipo usa para editar contenido y vender en línea.",
    tools: [
      "WordPress",
      "Sanity",
      "Contentful",
      "Strapi",
      "Payload",
      "Webflow",
      "Shopify",
      "Shopify Hydrogen",
      "WooCommerce",
    ],
  },
  {
    name: "Pruebas, rendimiento y monitoreo",
    plain: "Controles que detectan los problemas a tiempo y mantienen su sitio rápido y seguro.",
    tools: [
      "Playwright",
      "Cypress",
      "Vitest",
      "Jest",
      "Vite",
      "Turbopack",
      "Lighthouse",
      "Core Web Vitals",
      "Sentry",
      "Datadog",
      "PostHog",
      "Google Analytics 4",
      "Prácticas OWASP",
    ],
  },
];

const aiCatalog: TechGroup[] = [
  {
    name: "Modelos de IA",
    plain: "Los motores de IA que leen, escriben, resumen y razonan. Elegimos el adecuado para cada tarea.",
    tools: [
      "OpenAI GPT",
      "Modelos de razonamiento de la serie o de OpenAI",
      "Anthropic Claude",
      "Google Gemini",
      "Meta Llama",
      "Mistral",
      "DeepSeek",
      "Qwen",
      "Cohere",
      "xAI Grok",
    ],
  },
  {
    name: "Plataformas y alojamiento de IA",
    plain: "Entornos seguros para ejecutar IA, incluidas opciones que mantienen sus datos en su propia nube.",
    tools: [
      "Azure AI Foundry",
      "Azure OpenAI",
      "Amazon Bedrock",
      "Google Vertex AI",
      "Hugging Face",
      "Ollama",
      "vLLM",
      "Groq",
      "Together AI",
      "Replicate",
    ],
  },
  {
    name: "Agentes y frameworks",
    plain: "Piezas para crear asistentes de IA que pueden realizar acciones y usar sus herramientas.",
    tools: [
      "Model Context Protocol (MCP)",
      "OpenAI Agents SDK",
      "Claude Agent SDK",
      "Vercel AI SDK",
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "CrewAI",
      "AutoGen",
      "Pydantic AI",
      "DSPy",
    ],
  },
  {
    name: "Conocimiento y búsqueda",
    plain: "Para que la IA responda a partir de sus propios documentos, con fuentes que puede comprobar.",
    tools: [
      "Generación aumentada por recuperación (RAG)",
      "Embeddings",
      "pgvector",
      "Pinecone",
      "Weaviate",
      "Qdrant",
      "Chroma",
      "Azure AI Search",
      "Búsqueda híbrida y semántica",
    ],
  },
  {
    name: "Voz, visión y documentos",
    plain: "IA que entiende la voz, las imágenes y el papeleo, como facturas y contratos.",
    tools: [
      "OpenAI Whisper",
      "API de voz en tiempo real",
      "ElevenLabs",
      "Deepgram",
      "Azure Document Intelligence",
      "Amazon Textract",
      "Comprensión de imágenes",
      "Generación de imágenes",
    ],
  },
  {
    name: "Personalización",
    plain: "Enseñar a la IA su tono, su vocabulario y sus procesos cuando los resultados estándar no bastan.",
    tools: [
      "Ingeniería de prompts",
      "Salidas estructuradas",
      "Llamadas a funciones y herramientas",
      "Ajuste fino",
      "LoRA",
      "Destilación",
    ],
  },
  {
    name: "Evaluación y monitoreo",
    plain: "Medir la precisión y el costo para que los resultados de la IA sean fiables en producción.",
    tools: [
      "LangSmith",
      "Langfuse",
      "promptfoo",
      "Arize Phoenix",
      "Weights & Biases",
      "OpenTelemetry",
      "Conjuntos de prueba a medida",
    ],
  },
  {
    name: "Seguridad y privacidad",
    plain: "Controles que protegen sus datos y mantienen las respuestas de la IA dentro de las reglas.",
    tools: [
      "Barreras de protección",
      "Anonimización de datos personales",
      "Acceso basado en roles",
      "Flujos de revisión humana",
      "Registros de auditoría",
      "Opciones sin retención de datos",
    ],
  },
];

export const technology: TechnologyContent = { techStack, webCatalog, aiCatalog };
