import type { Ui } from "../en/ui";

/**
 * Texto de interfaz compartido, en español. Debe tener la misma forma que la versión en inglés
 * (véase `Ui`). Se trata de "usted", con frases cortas y el vocabulario del cliente.
 */
export const ui: Ui = {
  site: {
    description:
      "{name} es una empresa de desarrollo de software a medida y soluciones tecnológicas. Diseñamos, construimos y modernizamos la tecnología que ayuda a las empresas a operar, resolver problemas y crecer.",
    hours: "De lunes a viernes, de 9:00 a 18:00, hora del centro",
    shareImageAlt: "{name}: software a medida y soluciones tecnológicas",
    audienceType: "Empresas de todos los tamaños que necesitan software a medida y soluciones tecnológicas",
    countriesLabel: "Países donde trabajamos",
    countries: ["Estados Unidos", "Canadá", "México"],
    languagesLabel: "Idiomas",
    languages: "español, inglés y francés",
  },

  skipToContent: "Saltar al contenido",
  breadcrumbHome: "Inicio",
  breadcrumb: "Ruta de navegación",
  logoLabel: "Inicio de {name}",
  readMore: "Leer más",

  cta: {
    discuss: "Hablar de su proyecto",
    explore: "Explorar nuestras capacidades",
    startConversation: "Iniciar una conversación",
    audit: "Reservar una auditoría",
    auditLong: "Reservar una auditoría de sistemas digitales",
    snapshot: "Pedir una revisión gratuita",
    snapshotLong: "Pedir una revisión gratuita de su sitio",
    snapshotAlt: "O empiece con una revisión gratuita",
    replyPromise: "Una persona le responde en una hora hábil.",
    orEmail: "O escriba a",
  },

  closingCta: {
    title: "Construyamos juntos su próxima solución.",
    lead: "Ya sea que necesite una aplicación a medida, un sistema de software completo, infraestructura en la nube, integración de IA o ayuda para resolver un problema técnico existente, conversemos sobre lo que su negocio necesita.",
  },

  header: {
    mainNav: "Principal",
    mobileNav: "Móvil",
    home: "Inicio",
    openMenu: "Abrir el menú",
    closeMenu: "Cerrar el menú",
    language: "Idioma",
  },

  nav: {
    services: "Servicios",
    industries: "Sectores",
    audit: "Auditoría de sistemas digitales",
    work: "Trabajos",
    howWeWork: "Cómo trabajamos",
    about: "Nosotros",
    standards: "Estándares",
    insights: "Artículos",
    contact: "Contacto",
    partners: "Aliados",
    snapshot: "Revisión gratuita",
    websiteCheck: "Prueba de velocidad instantánea",
  },

  footer: {
    tagline: "Software a medida y soluciones tecnológicas.",
    services: "Servicios",
    industries: "Sectores",
    company: "Empresa",
    legal: "Información legal",
    contact: "Contacto",
    rights: "Todos los derechos reservados.",
    privacy: "Política de privacidad",
    terms: "Términos de uso",
    cookies: "Aviso de cookies",
    mexicoNotice: "Aviso de privacidad (México)",
  },

  price: {
    auditRange: "US${from} a US${to}",
    creditNote: "Se acredita por completo a un proyecto firmado dentro de {days} días.",
  },

  demo: {
    sampleData: "Datos de ejemplo a modo de ilustración",
  },

  sections: {
    problem: "El problema",
    changes: "Qué cambia",
    included: "Qué incluye",
    phases: "Cómo funciona, por fases",
    phase: "Fase {number}",
    price: "Precio",
    relatedDemo: "Demo relacionada",
    forWhom: "Para quién es",
    questions: "Preguntas frecuentes",
    otherServices: "Otros servicios",
    otherIndustries: "Otros sectores",
    relatedServices: "Servicios relacionados",
    inTheirWords: "En sus palabras",
    systemsWeBuild: "Los sistemas que construimos",
    softwareWeConnect: "Software al que nos conectamos",
    theDemo: "La demo para este sector",
    whatNext: "Qué sigue",
  },

  leadForm: {
    name: "Nombre",
    role: "Cargo",
    company: "Empresa",
    website: "Sitio web",
    websitePlaceholder: "suempresa.com",
    email: "Correo electrónico",
    phone: "Teléfono",
    need: "¿Qué quiere mejorar?",
    needHint:
      "Basta con una o dos frases. Por ejemplo: las consultas tardan demasiado en contestarse, o el personal vuelve a capturar los mismos datos.",
    emailBusiness: "Correo de trabajo",
    projectType: "Tipo de proyecto",
    projectTypePlaceholder: "Elija un tipo de proyecto",
    projectTypes: {
      "custom-software": "Software a medida",
      "web-applications": "Sitio web o aplicación web",
      "ai-solutions": "IA o automatización",
      "database-solutions": "Base de datos",
      "cloud-solutions": "Nube o infraestructura",
      "software-architecture": "Arquitectura o integración",
      "application-modernization": "Modernizar un sistema existente",
      "digital-transformation": "Transformación digital",
      "technology-consulting": "Consultoría o un problema técnico",
      "not-sure": "Todavía no lo sé",
    },
    needProject: "Describa el desafío",
    needProjectHint: "Bastan unas frases: qué intenta lograr, qué no funciona y qué sistemas intervienen.",
    scope: "Alcance estimado del proyecto",
    scopePlaceholder: "Todavía no lo sé",
    scopes: {
      exploring: "Solo estoy explorando opciones",
      focused: "Una corrección o función específica",
      project: "Una aplicación o un sistema",
      program: "Un esfuerzo mayor, con varios sistemas",
    },
    language: "Idioma preferido",
    optional: "Opcional",
    consent: "Acepto que {name} use estos datos para responderme.",
    privacyLink: "Política de privacidad",
    honeypot: "Deje este campo vacío",
    submit: {
      audit: "Reservar mi auditoría",
      contact: "Iniciar una conversación",
      snapshot: "Pedir mi revisión gratuita",
    },
    submitting: "Enviando…",
    sendingStatus: "Enviando su solicitud.",
    successTitle: {
      audit: "Gracias. Recibimos su solicitud de auditoría.",
      contact: "Gracias. Recibimos su consulta de proyecto.",
      snapshot: "Gracias. Recibimos su solicitud de revisión.",
    },
    successBody:
      "Una confirmación va en camino a su bandeja de entrada. Una persona le responderá personalmente en una hora hábil ({hours}). Si es urgente, escriba a",
    bookTitle: "¿Prefiere elegir usted el horario?",
    bookCall: "Elegir el horario de la llamada de descubrimiento",
    languageNames: { en: "English", fr: "Français", es: "Español" },
  },

  leadErrors: {
    nameRequired: "Introduzca su nombre.",
    nameTooLong: "Use un nombre de menos de {max} caracteres.",
    roleTooLong: "Use un cargo de menos de {max} caracteres.",
    companyTooLong: "Use un nombre de empresa de menos de {max} caracteres.",
    websiteInvalid: "Introduzca la dirección de un sitio web, como suempresa.com.",
    websiteRequired: "Introduzca la dirección de su sitio web.",
    emailRequired: "Introduzca su correo electrónico.",
    emailInvalid: "Introduzca un correo electrónico válido, como nombre@empresa.com.",
    projectTypeRequired: "Elija un tipo de proyecto.",
    phoneInvalid: "Introduzca un número de teléfono válido o deje este campo en blanco.",
    needTooShort: "Cuéntenos un poco más (al menos {min} caracteres).",
    needTooLong: "Use un texto de menos de {max} caracteres.",
    languageInvalid: "Elija un idioma.",
    consentRequired: "Marque la casilla para que podamos responderle.",
    rateLimited:
      "Ha enviado varias solicitudes en poco tiempo. Espere unos minutos o escríbanos a {email}.",
    fixFields: "Corrija los campos resaltados.",
    sendFailed: "No pudimos enviar su solicitud en este momento. Inténtelo de nuevo o escríbanos directamente a {email}.",
  },

  confirmation: {
    subject: "Recibimos su solicitud",
    greeting: "Hola, {name}:",
    kinds: {
      audit: "Gracias por su interés en una auditoría de sistemas digitales.",
      contact: "Gracias por contarnos sobre su proyecto.",
      snapshot: "Gracias por pedir una revisión gratuita de su sitio.",
    },
    automatic: "Esta es una confirmación automática, para que sepa que su solicitud nos llegó.",
    promise: "Una persona de nuestro equipo le responderá personalmente en una hora hábil ({hours}).",
    nextAudit: "Cuando reserve, le enviaremos un cuestionario breve para que la llamada se centre en su negocio.",
    nextSnapshot: "Le enviaremos tres observaciones concretas sobre su sitio, con lo que conviene hacer en cada caso.",
    signoff: "El equipo de {name}",
    ignore: "Si usted no hizo esta solicitud, puede ignorar este mensaje.",
  },

  newsletter: {
    title: "Notas prácticas sobre software, datos y nube para equipos de negocio",
    lead: "Un correo breve cada vez que publiquemos un artículo nuevo. Sin spam, y puede darse de baja con un clic.",
    email: "Correo electrónico",
    language: "Idioma de los correos",
    consent: "Acepto recibir correos de {name}. Puedo darme de baja en cualquier momento.",
    submit: "Suscribirme",
    submitting: "Suscribiendo…",
    successTitle: "Ya está suscrito.",
    successBody: "Gracias. Le escribiremos cuando haya algo nuevo que leer.",
    errors: {
      emailRequired: "Introduzca su correo electrónico.",
      emailInvalid: "Introduzca un correo electrónico válido, como nombre@empresa.com.",
      consentRequired: "Marque la casilla para suscribirse.",
      rateLimited: "Demasiados intentos. Inténtelo de nuevo en unos minutos.",
      failed: "No pudimos suscribirle en este momento. Inténtelo de nuevo en un momento.",
    },
  },

  contactPage: {
    metaTitle: "Contacto: hablemos de su proyecto",
    metaDescription:
      "Cuéntenos sobre su proyecto o desafío técnico: software a medida, aplicaciones web, IA, bases de datos, nube o modernización. Una persona le responde en una hora hábil.",
    eyebrow: "Contacto",
    title: "Construyamos juntos su próxima solución.",
    lead: "Ya sea que necesite una aplicación a medida, un sistema de software completo, infraestructura en la nube, integración de IA o ayuda para resolver un problema técnico existente, conversemos sobre lo que su negocio necesita.",
    nextTitle: "Qué sigue",
    nextSteps: [
      "Recibe de inmediato un correo de confirmación, en su idioma.",
      "Una persona le responde personalmente en una hora hábil.",
      "Agendamos una llamada para entender el problema antes de recomendar nada.",
    ],
    pickTime: "¿Prefiere elegir un horario?",
    bookCall: "Reservar una llamada de descubrimiento",
    reachDirectly: "¿Prefiere escribirnos directamente?",
    servingTitle: "Países e idiomas",
    servingBody: "Trabajamos con empresas de estos países: {countries}. Idiomas de atención: {languages}.",
  },

  bookPage: {
    metaTitle: "Reservar una llamada de descubrimiento",
    metaDescription:
      "Elija un horario para una llamada de descubrimiento sobre su proyecto o desafío técnico. Una persona confirma en una hora hábil.",
    eyebrow: "Reservar una llamada",
    title: "Elija el horario que mejor le convenga.",
    lead: "Una llamada de descubrimiento para hablar de su proyecto o problema. Aquí empezamos, y la llamada no tiene costo.",
    frameTitle: "Agendar una llamada de descubrimiento",
    trouble: "¿Tiene problemas con el calendario?",
    openInTab: "Ábralo en una pestaña nueva",
    or: "o",
    sendMessage: "envíenos un mensaje",
  },

  websiteCheckPage: {
    metaTitle: "Prueba de velocidad instantánea de su sitio web",
    metaDescription:
      "Ejecute una prueba automatizada de Google Lighthouse en su sitio. Vea las puntuaciones de velocidad, accesibilidad, buenas prácticas y SEO en un teléfono, y qué corregir primero.",
    eyebrow: "Prueba de velocidad instantánea",
    title: "Vea ahora mismo cómo funciona su sitio en un teléfono.",
    lead: "Una prueba automatizada que tarda menos de un minuto. Puntúa velocidad, accesibilidad, buenas prácticas y los fundamentos del SEO. Para la mirada de una persona sobre su sitio, pida la revisión gratuita.",
    whyTitle: "Qué significan las puntuaciones",
    whyBody:
      "La prueba simula un teléfono de gama media con conexión móvil. Es una prueba de laboratorio: una buena forma de encontrar problemas, no una promesa sobre lo que viven sus visitantes reales. Los datos de usuarios reales (Core Web Vitals) son un juez más justo.",
    points: [
      "Rendimiento: qué tan rápido cargan y responden sus páginas en un teléfono típico",
      "Accesibilidad: si las personas que usan lectores de pantalla o teclado pueden usar su sitio",
      "Buenas prácticas: seguridad y estándares web modernos",
      "SEO: si los buscadores pueden encontrar, leer y entender sus páginas",
    ],
    snapshotTitle: "¿Quiere que lo revise una persona?",
    snapshotBody: "La revisión gratuita le da tres observaciones concretas sobre su sitio, escritas por una persona.",
  },

  websiteCheck: {
    address: "Dirección del sitio web",
    placeholder: "suempresa.com",
    email: "Correo electrónico",
    optional: "Opcional",
    submit: "Ejecutar la prueba",
    submitting: "Analizando…",
    emailHint: "Añada su correo si desea que una persona le dé seguimiento a los resultados. Solo lo usaremos para eso.",
    running: "Estamos probando su sitio en un teléfono móvil simulado. Suele tardar entre 20 y 40 segundos.",
    resultsFor: "Resultados de {url}",
    resultsNote: "Prueba en móvil, puntuada sobre 100 por Google Lighthouse.",
    performance: "Rendimiento",
    accessibility: "Accesibilidad",
    bestPractices: "Buenas prácticas",
    seo: "SEO",
    loadingSpeed: "Velocidad de carga",
    fixFirst: "Qué corregir primero",
    noIssues:
      "No encontramos problemas importantes en esta prueba rápida. La revisión de una persona aún puede encontrar mejoras de contenido, conversión y gestión de consultas.",
    emailSent: "Gracias. Una persona le responderá en una hora hábil.",
    followUp: "¿Quiere ayuda con esto? Pida una revisión gratuita o reserve una auditoría de sistemas digitales.",
    talk: "Pedir una revisión gratuita",
    savings: "Podría ahorrar unos {seconds} s",
    metrics: {
      "largest-contentful-paint": "Largest Contentful Paint",
      "first-contentful-paint": "First Contentful Paint",
      "total-blocking-time": "Tiempo total de bloqueo",
      "cumulative-layout-shift": "Cumulative Layout Shift",
      "speed-index": "Índice de velocidad",
    },
    errors: {
      invalidUrl: "Introduzca una dirección web pública válida, como ejemplo.com.",
      invalidEmail: "Introduzca un correo electrónico válido o deje el campo en blanco.",
      rateLimited:
        "Ha realizado varias pruebas en la última hora. Inténtelo más tarde o pida una revisión gratuita.",
      failed: "No pudimos analizar ese sitio en este momento. Revise la dirección e inténtelo de nuevo en un minuto.",
    },
  },

  /** Etiquetas breves dibujadas en las ilustraciones. Son imágenes: cada etiqueta es una palabra sencilla. */
  visuals: {
    illustration: "Ilustración",
    alt: {
      hero: "Ilustración de un panel de una aplicación de negocio, las capas de arquitectura de software que lo respaldan y el entorno en la nube donde se ejecuta",
      "custom-software": "Ilustración de una aplicación de negocio a medida con un formulario de solicitud y una cola de trabajo",
      "web-applications": "Ilustración de un sitio web en un navegador de escritorio y en un teléfono móvil",
      "ai-solutions":
        "Ilustración de un flujo de trabajo con IA: una solicitud entrante, un modelo de IA que redacta una respuesta, una persona que la revisa y los sistemas de negocio conectados",
      "database-solutions": "Ilustración del diseño de una base de datos con tres tablas relacionadas",
      "cloud-solutions":
        "Ilustración de infraestructura en la nube: usuarios, un balanceador de carga, servidores de aplicación, una base de datos y almacenamiento dentro de una región de la nube",
      "software-architecture": "Ilustración de una arquitectura de software en capas: clientes, una capa de API, servicios y almacenes de datos",
      "application-modernization": "Ilustración de un sistema heredado reemplazado por una plataforma moderna en tres etapas",
      "digital-transformation": "Ilustración de un proceso manual que se convierte en un flujo de trabajo digital integrado",
      "technology-consulting": "Ilustración de un informe de evaluación técnica con hallazgos priorizados y un plan",
      integration:
        "Ilustración de aplicaciones web, móviles y de socios conectadas mediante una sola capa de API con una base de datos, sistemas de negocio y servicios de IA",
    },
    integration: {
      hub: "Capa de API",
      top: ["App web", "App móvil", "Socios"],
      bottom: ["Base de datos", "Sistemas de negocio", "Servicios de IA"],
    },
    app: {
      name: "Operaciones",
      tabs: ["Resumen", "Solicitudes", "Reportes"],
      kpis: ["Abiertas", "En revisión", "Completadas"],
      activity: "Actividad reciente",
      rows: ["Solicitud recibida", "Asignada al equipo", "Aprobada y cerrada"],
      status: ["Nueva", "Activa", "Lista"],
    },
    layers: { interface: "Interfaz", api: "API", services: "Servicios", data: "Datos" },
    cloud: {
      region: "Región de la nube",
      users: "Usuarios",
      balancer: "Balanceador de carga",
      app: "Aplicación",
      database: "Base de datos",
      storage: "Almacenamiento",
      monitoring: "Monitoreo",
    },
    ai: {
      input: "Solicitud entrante",
      model: "Modelo de IA",
      review: "Revisión humana",
      systems: "Sus sistemas",
      draft: "Respuesta sugerida",
      approved: "Aprobada",
      tasks: ["Redactar", "Clasificar", "Encaminar"],
    },
    web: { site: "Su sitio web", mobile: "Móvil" },
    custom: { title: "Nueva solicitud", fields: ["Cliente", "Tipo", "Notas"], submit: "Enviar", queue: "Cola de trabajo" },
    modern: {
      legacy: "Sistema heredado",
      modern: "Plataforma moderna",
      stage: "Etapa {number}",
      modules: ["Facturación", "Reportes", "Clientes"],
    },
    transform: {
      today: "Hoy",
      after: "Flujo de trabajo digital",
      manual: ["Formulario en papel", "Correo", "Hoja de cálculo"],
      steps: ["Solicitud", "Aprobación", "Actualización", "Reporte"],
    },
    assess: {
      title: "Evaluación técnica",
      findings: ["Consultas lentas en la base de datos", "Framework sin soporte", "Sin respaldos automáticos"],
      severity: ["Alta", "Media", "Baja"],
      plan: "Plan priorizado",
    },
  },

  notFound: {
    metaTitle: "Página no encontrada",
    title: "Esta página no existe.",
    lead: "Es posible que el enlace esté desactualizado o que la página se haya movido.",
    home: "Volver al inicio",
    contact: "Contáctenos",
  },

  assistant: {
    greeting:
      "¡Hola! Pregúnteme sobre nuestros servicios, cómo trabajamos o el tipo de proyecto que tiene en mente. También puedo orientarle hacia la capacidad adecuada.",
    open: "Haga una pregunta",
    close: "Cerrar",
    title: "Pregúntenos lo que quiera",
    disclaimer: "Asistente de IA. Las respuestas pueden contener errores, así que no comparta información sensible.",
    suggested: "Preguntas sugeridas",
    suggestions: [
      "¿Qué tipos de software desarrollan?",
      "¿Trabajan con IA y nube?",
      "¿Cómo empieza un proyecto?",
    ],
    you: "Usted: ",
    assistant: "Asistente: ",
    thinking: "Pensando…",
    limit: "Para cualquier otra cosa, una persona le ayudará con gusto.",
    book: "Hablar de su proyecto",
    inputLabel: "Su pregunta",
    placeholder: "Escriba su pregunta",
    send: "Enviar",
    failed: "Lo siento, no pude responder en este momento. Inténtelo de nuevo.",
    interrupted: "Lo siento, se interrumpió la conexión. Inténtelo de nuevo.",
    unavailable: "El asistente no está disponible en este momento.",
    wrongOrigin: "Las solicitudes deben provenir de este sitio web.",
    rateLimited: "Ha enviado muchos mensajes en poco tiempo. Inténtelo de nuevo en unos minutos.",
    invalid: "No se pudo enviar ese mensaje. Pruebe con una pregunta más corta.",
    declined:
      "Lo siento, no puedo ayudarle con eso. Para cualquier otra cosa, escriba a {email} o contáctenos en {contact}.",
    serverError: "Lo siento, algo salió mal de nuestro lado. Inténtelo de nuevo o escriba a {email}.",
    replyLanguage: 'Spanish, using the formal "usted", in a plain and friendly tone',
  },
};
