import type { TechGroup, TechnologyContent } from "@/lib/technology";

/** Technology we work with, grouped by layer. Shown on the homepage. */
const techStack: TechGroup[] = [
  {
    name: "Front end",
    plain: "Les pages et les écrans que vos clients voient et utilisent.",
    tools: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Astro", "Vue", "Tailwind CSS"],
  },
  {
    name: "Back end et API",
    plain: "La logique en coulisses qui enregistre les données, envoie les courriels et relie les systèmes.",
    tools: ["Node.js", "Python", "Go", "API REST", "GraphQL", "WebSockets", "Fonctions serverless"],
  },
  {
    name: "Bases de données",
    plain: "L'endroit où votre information est stockée en sécurité et retrouvée rapidement.",
    tools: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Supabase", "Prisma", "Elasticsearch"],
  },
  {
    name: "IA et apprentissage automatique",
    plain:
      "Des assistants et des outils qui lisent, écrivent, classent et répondent à des questions à partir de vos données.",
    tools: [
      "OpenAI",
      "Anthropic Claude",
      "Google Gemini",
      "Modèles à poids ouverts (Llama, Mistral)",
      "Génération augmentée par récupération",
      "Recherche vectorielle (pgvector)",
      "LangChain",
      "Évaluation et surveillance",
    ],
  },
  {
    name: "Infonuagique et DevOps",
    plain: "Un hébergement fiable, des sauvegardes automatiques et des mises en production sûres et reproductibles.",
    tools: ["AWS", "Microsoft Azure", "Google Cloud", "Vercel", "Cloudflare", "Docker", "GitHub Actions", "Terraform"],
  },
  {
    name: "Contenu, commerce et paiements",
    plain: "Les outils que votre équipe utilise pour modifier le site, vendre en ligne et encaisser les paiements.",
    tools: ["WordPress", "Sanity", "Contentful", "Shopify", "Stripe", "Webflow"],
  },
  {
    name: "Automatisation et intégrations",
    plain: "Des connexions qui font circuler l'information entre les logiciels que vous utilisez déjà.",
    tools: ["n8n", "Make", "Zapier", "Salesforce", "HubSpot", "NetSuite", "QuickBooks", "Microsoft 365", "Slack"],
  },
  {
    name: "Qualité, sécurité et performance",
    plain: "Des tests et une surveillance qui repèrent les problèmes avant vos clients.",
    tools: [
      "Playwright",
      "Vitest",
      "Lighthouse",
      "Core Web Vitals",
      "Sentry",
      "Pratiques OWASP",
      "Accessibilité (WCAG 2.2)",
    ],
  },
];

/** Full catalog shown on the Technology page, split into web and AI. */
const webCatalog: TechGroup[] = [
  {
    name: "Langages",
    plain: "Les langages de base dans lesquels le Web et les logiciels modernes sont écrits.",
    tools: ["HTML5", "CSS3", "JavaScript (ES2025)", "TypeScript", "Python", "Go", "Rust", "PHP", "C#", "SQL"],
  },
  {
    name: "Frameworks front end",
    plain: "Des frameworks qui transforment les maquettes en pages et en applications rapides et interactives.",
    tools: [
      "React 19",
      "Next.js",
      "Vue",
      "Nuxt",
      "Svelte",
      "SvelteKit",
      "Angular",
      "Astro",
      "React Router (Remix)",
      "SolidJS",
      "htmx",
    ],
  },
  {
    name: "Styles et interface",
    plain: "L'apparence de votre produit et sa cohérence sur toutes les tailles d'écran.",
    tools: [
      "Tailwind CSS",
      "Sass",
      "CSS Modules",
      "shadcn/ui",
      "Radix UI",
      "Headless UI",
      "Framer Motion",
      "Figma",
      "Storybook",
    ],
  },
  {
    name: "Mobile et bureau",
    plain: "Des applications pour téléphones et ordinateurs qui partagent du code avec votre site web.",
    tools: ["React Native", "Expo", "Applications web progressives", "Flutter", "Capacitor", "Electron", "Tauri"],
  },
  {
    name: "Back end et environnements d'exécution",
    plain: "Les serveurs et la logique derrière votre produit : comptes, commandes, courriels et plus encore.",
    tools: ["Node.js", "Bun", "Deno", "Express", "Fastify", "NestJS", "Hono", "Django", "FastAPI", "Laravel", ".NET"],
  },
  {
    name: "API et temps réel",
    plain: "La façon dont vos systèmes communiquent entre eux et se mettent à jour instantanément.",
    tools: ["REST", "GraphQL", "tRPC", "gRPC", "WebSockets", "Server-Sent Events", "Webhooks", "OpenAPI"],
  },
  {
    name: "Bases de données et données",
    plain: "L'endroit où votre information est stockée, consultée et protégée.",
    tools: [
      "PostgreSQL",
      "MySQL",
      "SQL Server",
      "SQLite",
      "MongoDB",
      "Redis",
      "Supabase",
      "Firebase",
      "Neon",
      "Elasticsearch",
      "ClickHouse",
      "Prisma",
      "Drizzle ORM",
    ],
  },
  {
    name: "Infonuagique, hébergement et DevOps",
    plain: "Un hébergement fiable, des sauvegardes automatiques et des mises en production sûres et reproductibles.",
    tools: [
      "AWS",
      "Microsoft Azure",
      "Google Cloud",
      "Vercel",
      "Netlify",
      "Cloudflare Workers",
      "Fly.io",
      "DigitalOcean",
      "Docker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "GitLab CI",
    ],
  },
  {
    name: "Authentification et paiements",
    plain: "Une connexion sécurisée pour vos utilisateurs et des moyens fiables d'être payé.",
    tools: ["Auth.js", "Clerk", "Auth0", "Microsoft Entra ID", "Passkeys", "OAuth 2.0", "Stripe", "PayPal", "Square"],
  },
  {
    name: "CMS et commerce électronique",
    plain: "Les outils que votre équipe utilise pour modifier le contenu et vendre en ligne.",
    tools: [
      "WordPress",
      "Sanity",
      "Contentful",
      "Strapi",
      "Payload",
      "Webflow",
      "Shopify",
      "Shopify Hydrogen",
      "WooCommerce",
    ],
  },
  {
    name: "Tests, performance et surveillance",
    plain: "Des vérifications qui détectent les problèmes tôt et gardent votre site rapide et sécuritaire.",
    tools: [
      "Playwright",
      "Cypress",
      "Vitest",
      "Jest",
      "Vite",
      "Turbopack",
      "Lighthouse",
      "Core Web Vitals",
      "Sentry",
      "Datadog",
      "PostHog",
      "Google Analytics 4",
      "Pratiques OWASP",
    ],
  },
];

const aiCatalog: TechGroup[] = [
  {
    name: "Modèles d'IA",
    plain: "Les moteurs d'IA qui lisent, écrivent, résument et raisonnent. Nous choisissons le bon pour chaque tâche.",
    tools: [
      "OpenAI GPT",
      "Modèles de raisonnement de la série o d'OpenAI",
      "Anthropic Claude",
      "Google Gemini",
      "Meta Llama",
      "Mistral",
      "DeepSeek",
      "Qwen",
      "Cohere",
      "xAI Grok",
    ],
  },
  {
    name: "Plateformes et hébergement d'IA",
    plain:
      "Des environnements sécurisés pour exécuter l'IA, y compris des options qui gardent vos données dans votre propre nuage.",
    tools: [
      "Azure AI Foundry",
      "Azure OpenAI",
      "Amazon Bedrock",
      "Google Vertex AI",
      "Hugging Face",
      "Ollama",
      "vLLM",
      "Groq",
      "Together AI",
      "Replicate",
    ],
  },
  {
    name: "Agents et frameworks",
    plain: "Les briques pour créer des assistants d'IA capables d'agir et d'utiliser vos outils.",
    tools: [
      "Model Context Protocol (MCP)",
      "OpenAI Agents SDK",
      "Claude Agent SDK",
      "Vercel AI SDK",
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "CrewAI",
      "AutoGen",
      "Pydantic AI",
      "DSPy",
    ],
  },
  {
    name: "Connaissances et recherche",
    plain: "Permettre à l'IA de répondre à partir de vos propres documents, avec des sources vérifiables.",
    tools: [
      "Génération augmentée par récupération (RAG)",
      "Plongements (embeddings)",
      "pgvector",
      "Pinecone",
      "Weaviate",
      "Qdrant",
      "Chroma",
      "Azure AI Search",
      "Recherche hybride et sémantique",
    ],
  },
  {
    name: "Voix, vision et documents",
    plain: "Une IA qui comprend la parole, les images et les documents comme les factures et les contrats.",
    tools: [
      "OpenAI Whisper",
      "API vocales en temps réel",
      "ElevenLabs",
      "Deepgram",
      "Azure Document Intelligence",
      "Amazon Textract",
      "Compréhension d'images",
      "Génération d'images",
    ],
  },
  {
    name: "Personnalisation",
    plain:
      "Enseigner à l'IA votre ton, votre vocabulaire et vos processus quand les résultats standards ne suffisent pas.",
    tools: [
      "Ingénierie de requêtes",
      "Sorties structurées",
      "Appels de fonctions et d'outils",
      "Ajustement fin",
      "LoRA",
      "Distillation",
    ],
  },
  {
    name: "Évaluation et surveillance",
    plain: "Mesurer la précision et les coûts pour que les résultats de l'IA soient fiables en production.",
    tools: [
      "LangSmith",
      "Langfuse",
      "promptfoo",
      "Arize Phoenix",
      "Weights & Biases",
      "OpenTelemetry",
      "Jeux de tests sur mesure",
    ],
  },
  {
    name: "Sécurité et confidentialité",
    plain: "Des contrôles qui protègent vos données et gardent les réponses de l'IA dans les règles.",
    tools: [
      "Garde-fous",
      "Caviardage des renseignements personnels",
      "Accès selon les rôles",
      "Flux de révision humaine",
      "Journalisation d'audit",
      "Options sans conservation de données",
    ],
  },
];

export const technology: TechnologyContent = { techStack, webCatalog, aiCatalog };
