import type { Ui } from "../en/ui";

/**
 * Texte d'interface partagé, en français du Québec. Il doit avoir la même forme que la version
 * anglaise (voir `Ui`). Vouvoiement, « courriel », phrases courtes et vocabulaire du client.
 */
export const ui: Ui = {
  site: {
    description:
      "{name} est une entreprise de développement de logiciels sur mesure et de solutions technologiques. Nous concevons, construisons et modernisons la technologie qui aide les entreprises à fonctionner, à résoudre des problèmes et à croître.",
    hours: "Du lundi au vendredi, de 9 h à 18 h, heure du Centre",
    shareImageAlt: "{name} : logiciels sur mesure et solutions technologiques",
    audienceType: "Entreprises de toutes tailles qui ont besoin de logiciels sur mesure et de solutions technologiques",
    countriesLabel: "Pays desservis",
    countries: ["États-Unis", "Canada", "Mexique"],
    languagesLabel: "Langues",
    languages: "français, anglais et espagnol",
  },

  skipToContent: "Passer au contenu",
  breadcrumbHome: "Accueil",
  breadcrumb: "Fil d'Ariane",
  logoLabel: "Accueil {name}",
  readMore: "En savoir plus",

  cta: {
    discuss: "Discuter de votre projet",
    explore: "Découvrir nos capacités",
    startConversation: "Lancer la conversation",
    audit: "Réserver un audit",
    auditLong: "Réserver un audit des systèmes numériques",
    snapshot: "Obtenir un aperçu gratuit",
    snapshotLong: "Obtenir un aperçu gratuit de votre site",
    snapshotAlt: "Ou commencez par un aperçu gratuit",
    replyPromise: "Une personne vous répond en moins d'une heure ouvrable.",
    orEmail: "Ou écrivez à",
  },

  closingCta: {
    title: "Concevons ensemble votre prochaine solution.",
    lead: "Que vous ayez besoin d'une application sur mesure, d'un système logiciel complet, d'une infrastructure infonuagique, d'une intégration de l'IA ou d'aide pour régler un problème technique existant, discutons de ce dont votre entreprise a besoin.",
  },

  header: {
    mainNav: "Principale",
    mobileNav: "Mobile",
    home: "Accueil",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    language: "Langue",
  },

  nav: {
    services: "Services",
    industries: "Secteurs",
    audit: "Audit des systèmes numériques",
    work: "Réalisations",
    howWeWork: "Notre façon de travailler",
    about: "À propos",
    standards: "Normes",
    insights: "Perspectives",
    contact: "Contact",
    partners: "Partenaires",
    snapshot: "Aperçu gratuit",
    websiteCheck: "Test de vitesse instantané",
  },

  footer: {
    tagline: "Logiciels sur mesure et solutions technologiques.",
    services: "Services",
    industries: "Secteurs",
    company: "Entreprise",
    legal: "Renseignements juridiques",
    contact: "Contact",
    rights: "Tous droits réservés.",
    privacy: "Politique de confidentialité",
    terms: "Conditions d'utilisation",
    cookies: "Avis sur les témoins",
    mexicoNotice: "Aviso de privacidad (Mexique)",
  },

  price: {
    auditRange: "de {from} à {to} $ US",
    creditNote: "Crédité en totalité à un projet signé dans les {days} jours.",
  },

  demo: {
    sampleData: "Données fictives à titre d'illustration",
  },

  sections: {
    problem: "Le problème",
    changes: "Ce qui change",
    included: "Ce qui est inclus",
    phases: "Comment ça se passe, par phases",
    phase: "Phase {number}",
    price: "Prix",
    relatedDemo: "Démo connexe",
    forWhom: "À qui s'adresse ce service",
    questions: "Questions fréquentes",
    otherServices: "Autres services",
    otherIndustries: "Autres secteurs",
    relatedServices: "Services connexes",
    inTheirWords: "Dans leurs mots",
    systemsWeBuild: "Les systèmes que nous construisons",
    softwareWeConnect: "Logiciels auxquels nous nous connectons",
    theDemo: "La démo pour ce secteur",
    whatNext: "La suite",
  },

  leadForm: {
    name: "Nom",
    role: "Fonction",
    company: "Entreprise",
    website: "Site web",
    websitePlaceholder: "votreentreprise.com",
    email: "Courriel",
    phone: "Téléphone",
    need: "Qu'aimeriez-vous corriger?",
    needHint:
      "Une ou deux phrases suffisent. Par exemple : les demandes attendent trop longtemps, ou le personnel ressaisit les mêmes données.",
    emailBusiness: "Courriel professionnel",
    projectType: "Type de projet",
    projectTypePlaceholder: "Choisissez un type de projet",
    projectTypes: {
      "custom-software": "Logiciel sur mesure",
      "web-applications": "Site web ou application web",
      "ai-solutions": "IA ou automatisation",
      "database-solutions": "Base de données",
      "cloud-solutions": "Infonuagique ou infrastructure",
      "software-architecture": "Architecture ou intégration",
      "application-modernization": "Modernisation d'un système existant",
      "digital-transformation": "Transformation numérique",
      "technology-consulting": "Conseil ou problème technique",
      "not-sure": "Pas encore certain",
    },
    needProject: "Décrivez le défi",
    needProjectHint: "Quelques phrases suffisent : ce que vous cherchez à faire, ce qui ne fonctionne pas et quels systèmes sont concernés.",
    scope: "Portée estimée du projet",
    scopePlaceholder: "Pas encore certain",
    scopes: {
      exploring: "J'explore simplement les options",
      focused: "Un correctif ou une fonction précise",
      project: "Une application ou un système",
      program: "Un effort plus vaste, sur plusieurs systèmes",
    },
    language: "Langue préférée",
    optional: "Facultatif",
    consent: "J'accepte que {name} utilise ces renseignements pour me répondre.",
    privacyLink: "Politique de confidentialité",
    honeypot: "Laissez ce champ vide",
    submit: {
      audit: "Réserver mon audit",
      contact: "Lancer la conversation",
      snapshot: "Obtenir mon aperçu gratuit",
    },
    submitting: "Envoi en cours…",
    sendingStatus: "Envoi de votre demande en cours.",
    successTitle: {
      audit: "Merci. Nous avons bien reçu votre demande d'audit.",
      contact: "Merci. Nous avons bien reçu votre demande de projet.",
      snapshot: "Merci. Nous avons bien reçu votre demande d'aperçu.",
    },
    successBody:
      "Une confirmation est en route vers votre boîte de réception. Une personne vous répondra personnellement en moins d'une heure ouvrable ({hours}). Si c'est urgent, écrivez à",
    bookTitle: "Vous préférez choisir l'heure vous-même?",
    bookCall: "Choisir l'heure de l'appel de découverte",
    languageNames: { en: "English", fr: "Français", es: "Español" },
  },

  leadErrors: {
    nameRequired: "Veuillez entrer votre nom.",
    nameTooLong: "Veuillez limiter votre nom à {max} caractères.",
    roleTooLong: "Veuillez limiter votre fonction à {max} caractères.",
    companyTooLong: "Veuillez limiter le nom de l'entreprise à {max} caractères.",
    websiteInvalid: "Veuillez entrer une adresse de site web, comme votreentreprise.com.",
    websiteRequired: "Veuillez entrer l'adresse de votre site web.",
    emailRequired: "Veuillez entrer votre adresse courriel.",
    emailInvalid: "Veuillez entrer une adresse courriel valide, comme nom@entreprise.com.",
    projectTypeRequired: "Veuillez choisir un type de projet.",
    phoneInvalid: "Veuillez entrer un numéro de téléphone valide, ou laissez ce champ vide.",
    needTooShort: "Dites-nous-en un peu plus (au moins {min} caractères).",
    needTooLong: "Veuillez limiter ce texte à {max} caractères.",
    languageInvalid: "Veuillez choisir une langue.",
    consentRequired: "Veuillez cocher la case pour que nous puissions vous répondre.",
    rateLimited:
      "Vous avez envoyé plusieurs demandes en peu de temps. Veuillez patienter quelques minutes ou nous écrire à {email}.",
    fixFields: "Veuillez corriger les champs en surbrillance.",
    sendFailed: "Nous n'avons pas pu envoyer votre demande pour le moment. Réessayez ou écrivez-nous directement à {email}.",
  },

  confirmation: {
    subject: "Nous avons bien reçu votre demande",
    greeting: "Bonjour {name},",
    kinds: {
      audit: "Merci de votre intérêt pour un audit des systèmes numériques.",
      contact: "Merci de nous avoir parlé de votre projet.",
      snapshot: "Merci d'avoir demandé un aperçu gratuit de votre site.",
    },
    automatic: "Ceci est une confirmation automatique, pour vous assurer que votre demande nous est parvenue.",
    promise: "Une personne de notre équipe vous répondra personnellement en moins d'une heure ouvrable ({hours}).",
    nextAudit: "Une fois votre rendez-vous réservé, nous vous enverrons un court questionnaire pour que l'appel porte sur votre entreprise.",
    nextSnapshot: "Nous vous enverrons trois observations précises sur votre site, avec ce qu'il faut faire pour chacune.",
    signoff: "L'équipe de {name}",
    ignore: "Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer ce message.",
  },

  newsletter: {
    title: "Des notes pratiques sur le logiciel, les données et l'infonuagique pour les équipes d'affaires",
    lead: "Un court courriel à chaque nouvel article. Pas de pourriel, et vous pouvez vous désabonner d'un clic.",
    email: "Courriel",
    language: "Langue des courriels",
    consent: "J'accepte de recevoir des courriels de {name}. Je peux me désabonner en tout temps.",
    submit: "S'abonner",
    submitting: "Abonnement en cours…",
    successTitle: "Vous êtes abonné.",
    successBody: "Merci. Nous vous écrirons quand il y aura du nouveau à lire.",
    errors: {
      emailRequired: "Veuillez entrer votre adresse courriel.",
      emailInvalid: "Veuillez entrer une adresse courriel valide, comme nom@entreprise.com.",
      consentRequired: "Veuillez cocher la case pour vous abonner.",
      rateLimited: "Trop de tentatives. Réessayez dans quelques minutes.",
      failed: "Nous n'avons pas pu vous abonner pour le moment. Réessayez dans un instant.",
    },
  },

  contactPage: {
    metaTitle: "Contact : discutons de votre projet",
    metaDescription:
      "Parlez-nous de votre projet ou de votre défi technique : logiciel sur mesure, applications web, IA, bases de données, infonuagique ou modernisation. Une personne vous répond en moins d'une heure ouvrable.",
    eyebrow: "Contact",
    title: "Concevons ensemble votre prochaine solution.",
    lead: "Que vous ayez besoin d'une application sur mesure, d'un système logiciel complet, d'une infrastructure infonuagique, d'une intégration de l'IA ou d'aide pour régler un problème technique existant, discutons de ce dont votre entreprise a besoin.",
    nextTitle: "La suite",
    nextSteps: [
      "Vous recevez tout de suite un courriel de confirmation, dans votre langue.",
      "Une personne vous répond personnellement en moins d'une heure ouvrable.",
      "Nous fixons un appel pour comprendre le problème avant de recommander quoi que ce soit.",
    ],
    pickTime: "Vous préférez choisir l'heure?",
    bookCall: "Réserver un appel de découverte",
    reachDirectly: "Vous préférez nous écrire directement?",
    servingTitle: "Pays et langues",
    servingBody: "Nous servons des entreprises dans les pays suivants : {countries}. Langues de service : {languages}.",
  },

  bookPage: {
    metaTitle: "Réserver un appel de découverte",
    metaDescription:
      "Choisissez l'heure d'un appel de découverte au sujet de votre projet ou de votre défi technique. Une personne confirme en moins d'une heure ouvrable.",
    eyebrow: "Réserver un appel",
    title: "Choisissez l'heure qui vous convient.",
    lead: "Un appel de découverte pour discuter de votre projet ou de votre problème. C'est là que nous commençons, et l'appel est gratuit.",
    frameTitle: "Planifier un appel de découverte",
    trouble: "Un problème avec le calendrier?",
    openInTab: "Ouvrez-le dans un nouvel onglet",
    or: "ou",
    sendMessage: "envoyez-nous un message",
  },

  websiteCheckPage: {
    metaTitle: "Test de vitesse instantané de votre site",
    metaDescription:
      "Lancez un test automatisé Google Lighthouse sur votre site. Consultez les notes de vitesse, d'accessibilité, de bonnes pratiques et de référencement sur mobile, et ce qu'il faut corriger en premier.",
    eyebrow: "Test de vitesse instantané",
    title: "Voyez tout de suite comment votre site se comporte sur un téléphone.",
    lead: "Un test automatisé qui prend moins d'une minute. Il note la vitesse, l'accessibilité, les bonnes pratiques et les bases du référencement. Pour le regard d'une personne sur votre site, demandez l'aperçu gratuit.",
    whyTitle: "Ce que signifient les notes",
    whyBody:
      "Le test simule un téléphone de milieu de gamme sur une connexion mobile. C'est un test en laboratoire : un bon moyen de repérer des problèmes, pas une promesse sur ce que vivent vos vrais visiteurs. Les données d'utilisateurs réels (Core Web Vitals) sont un juge plus équitable.",
    points: [
      "Performance : la rapidité avec laquelle vos pages se chargent et réagissent sur un téléphone typique",
      "Accessibilité : la capacité des personnes qui utilisent un lecteur d'écran ou un clavier à se servir de votre site",
      "Bonnes pratiques : sécurité et normes web modernes",
      "SEO : la capacité des moteurs de recherche à trouver, lire et comprendre vos pages",
    ],
    snapshotTitle: "Vous voulez qu'une personne y jette un coup d'œil?",
    snapshotBody: "L'aperçu gratuit vous donne trois observations précises sur votre site, rédigées par une personne.",
  },

  websiteCheck: {
    address: "Adresse du site web",
    placeholder: "votreentreprise.com",
    email: "Courriel",
    optional: "Facultatif",
    submit: "Lancer le test",
    submitting: "Analyse en cours…",
    emailHint:
      "Ajoutez votre courriel si vous souhaitez qu'une personne fasse un suivi des résultats. Nous l'utiliserons uniquement à cette fin.",
    running: "Nous testons votre site sur un téléphone mobile simulé. Cela prend habituellement de 20 à 40 secondes.",
    resultsFor: "Résultats pour {url}",
    resultsNote: "Test sur mobile, noté sur 100 par Google Lighthouse.",
    performance: "Performance",
    accessibility: "Accessibilité",
    bestPractices: "Bonnes pratiques",
    seo: "SEO",
    loadingSpeed: "Vitesse de chargement",
    fixFirst: "À corriger en premier",
    noIssues:
      "Aucun problème majeur relevé par ce test rapide. Le regard d'une personne peut tout de même révéler des améliorations du contenu, des conversions et du parcours des demandes.",
    emailSent: "Merci. Une personne vous répondra en moins d'une heure ouvrable.",
    followUp: "Vous voulez de l'aide pour ces points? Demandez un aperçu gratuit ou réservez un audit des systèmes numériques.",
    talk: "Obtenir un aperçu gratuit",
    savings: "Économie possible d'environ {seconds} s",
    metrics: {
      "largest-contentful-paint": "Largest Contentful Paint",
      "first-contentful-paint": "First Contentful Paint",
      "total-blocking-time": "Temps de blocage total",
      "cumulative-layout-shift": "Cumulative Layout Shift",
      "speed-index": "Indice de vitesse",
    },
    errors: {
      invalidUrl: "Veuillez entrer une adresse web publique valide, comme exemple.com.",
      invalidEmail: "Veuillez entrer une adresse courriel valide, ou laissez le champ vide.",
      rateLimited:
        "Vous avez lancé plusieurs tests au cours de la dernière heure. Réessayez plus tard ou demandez un aperçu gratuit.",
      failed: "Nous n'avons pas pu analyser ce site pour le moment. Vérifiez l'adresse et réessayez dans une minute.",
    },
  },

  /** Courts libellés dessinés dans les illustrations. Ce sont des images : chaque libellé est un mot simple. */
  visuals: {
    illustration: "Illustration",
    alt: {
      hero: "Illustration d'un tableau de bord d'application d'affaires, des couches d'architecture logicielle qui le soutiennent et de l'environnement infonuagique où il roule",
      "custom-software": "Illustration d'une application d'affaires sur mesure avec un formulaire de demande et une file de travail",
      "web-applications": "Illustration d'un site web dans un navigateur de bureau et sur un téléphone mobile",
      "ai-solutions":
        "Illustration d'un flux de travail d'IA : une demande entrante, un modèle d'IA qui rédige une réponse, une personne qui la révise et les systèmes d'affaires reliés",
      "database-solutions": "Illustration d'une base de données conçue avec trois tables reliées",
      "cloud-solutions":
        "Illustration d'une infrastructure infonuagique : des utilisateurs, un répartiteur de charge, des serveurs d'application, une base de données et du stockage dans une région infonuagique",
      "software-architecture": "Illustration d'une architecture logicielle en couches : clients, couche d'API, services et magasins de données",
      "application-modernization": "Illustration d'un système hérité remplacé par une plateforme moderne en trois étapes",
      "digital-transformation": "Illustration d'un processus manuel qui devient un flux de travail numérique intégré",
      "technology-consulting": "Illustration d'un rapport d'évaluation technique avec des constats priorisés et un plan",
      integration:
        "Illustration d'applications web, mobiles et de partenaires reliées par une seule couche d'API à une base de données, à des systèmes d'affaires et à des services d'IA",
    },
    integration: {
      hub: "Couche d'API",
      top: ["Application web", "Application mobile", "Partenaires"],
      bottom: ["Base de données", "Systèmes d'affaires", "Services d'IA"],
    },
    app: {
      name: "Exploitation",
      tabs: ["Aperçu", "Demandes", "Rapports"],
      kpis: ["Ouvertes", "En révision", "Terminées"],
      activity: "Activité récente",
      rows: ["Demande reçue", "Assignée à l'équipe", "Approuvée et fermée"],
      status: ["Nouvelle", "En cours", "Terminée"],
    },
    layers: { interface: "Interface", api: "API", services: "Services", data: "Données" },
    cloud: {
      region: "Région infonuagique",
      users: "Utilisateurs",
      balancer: "Répartiteur de charge",
      app: "Application",
      database: "Base de données",
      storage: "Stockage",
      monitoring: "Surveillance",
    },
    ai: {
      input: "Demande entrante",
      model: "Modèle d'IA",
      review: "Révision humaine",
      systems: "Vos systèmes",
      draft: "Réponse suggérée",
      approved: "Approuvée",
      tasks: ["Rédiger", "Classer", "Acheminer"],
    },
    web: { site: "Votre site web", mobile: "Mobile" },
    custom: { title: "Nouvelle demande", fields: ["Client", "Type", "Notes"], submit: "Soumettre", queue: "File d'attente" },
    modern: {
      legacy: "Système hérité",
      modern: "Plateforme moderne",
      stage: "Étape {number}",
      modules: ["Facturation", "Rapports", "Clients"],
    },
    transform: {
      today: "Aujourd'hui",
      after: "Flux de travail numérique",
      manual: ["Formulaire papier", "Courriel", "Chiffrier"],
      steps: ["Demande", "Approbation", "Mise à jour", "Rapport"],
    },
    assess: {
      title: "Évaluation technique",
      findings: ["Requêtes lentes sur la base de données", "Cadre logiciel non supporté", "Aucune sauvegarde automatique"],
      severity: ["Élevée", "Moyenne", "Faible"],
      plan: "Plan priorisé",
    },
  },

  notFound: {
    metaTitle: "Page introuvable",
    title: "Cette page n'existe pas.",
    lead: "Le lien est peut-être périmé, ou la page a été déplacée.",
    home: "Retour à l'accueil",
    contact: "Nous joindre",
  },

  assistant: {
    greeting:
      "Bonjour! Posez-moi vos questions sur nos services, notre façon de travailler ou le genre de projet que vous avez en tête. Je peux aussi vous orienter vers la bonne capacité.",
    open: "Poser une question",
    close: "Fermer",
    title: "Posez-nous vos questions",
    disclaimer:
      "Assistant IA. Les réponses peuvent comporter des erreurs, alors ne communiquez pas de renseignements sensibles.",
    suggested: "Questions suggérées",
    suggestions: [
      "Quels types de logiciels concevez-vous?",
      "Travaillez-vous avec l'IA et l'infonuagique?",
      "Comment un projet démarre-t-il?",
    ],
    you: "Vous : ",
    assistant: "Assistant : ",
    thinking: "Réflexion…",
    limit: "Pour la suite, une personne se fera un plaisir de vous aider.",
    book: "Discuter de votre projet",
    inputLabel: "Votre question",
    placeholder: "Tapez votre question",
    send: "Envoyer",
    failed: "Désolé, je n'ai pas pu répondre pour le moment. Veuillez réessayer.",
    interrupted: "Désolé, la connexion a été interrompue. Veuillez réessayer.",
    unavailable: "L'assistant n'est pas disponible pour le moment.",
    wrongOrigin: "Les demandes doivent provenir de ce site web.",
    rateLimited: "Vous avez envoyé beaucoup de messages en peu de temps. Réessayez dans quelques minutes.",
    invalid: "Ce message n'a pas pu être envoyé. Essayez une question plus courte.",
    declined:
      "Désolé, je ne peux pas vous aider avec cela. Pour toute autre question, écrivez à {email} ou joignez-nous à {contact}.",
    serverError: "Désolé, un problème est survenu de notre côté. Réessayez ou écrivez à {email}.",
    replyLanguage: 'French, using "vous", in a plain and friendly tone suited to North American readers (Quebec)',
  },
};
